# Generated by Django 3.1.7 on 2021-03-05 03:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='用户名')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('sex', models.BooleanField(verbose_name='性别')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注描述')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建日期')),
                ('relation_user', models.ManyToManyField(null=True, to='app.User', verbose_name='关联的人')),
            ],
            options={
                'verbose_name': '用户',
            },
        ),
    ]
