# Generated by Django 3.1.7 on 2021-03-05 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210305_0311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='relation_user',
        ),
        migrations.AddField(
            model_name='user',
            name='relation_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.user', verbose_name='关联的人'),
        ),
    ]
